# Generated by Django 4.2.18 on 2026-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_managerprofile_password_plain_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='password_plain',
            field=models.CharField(blank=True, default='', help_text='Пароль для отображения администратору', max_length=128),
        ),
    ]
