# Generated by Django 4.2.18 on 2026-03-01 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(help_text='Stream/group number', unique=True)),
                ('group_type', models.CharField(choices=[('1.5h', '1.5 hours'), ('2.5h', '2.5 hours')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('recruitment', 'Recruitment'), ('active', 'Active'), ('completed', 'Completed')], default='recruitment', max_length=20)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='trainers.trainer')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['-number'],
                'indexes': [models.Index(fields=['status'], name='groups_grou_status_952d41_idx'), models.Index(fields=['trainer'], name='groups_grou_trainer_29268a_idx')],
            },
        ),
    ]
