# Generated by Django 4.2.18 on 2026-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_online_subscription_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, choices=[('1.5h', '1.5 hours'), ('2.5h', '2.5 hours')], default='', help_text='Для офлайн обязателен; для онлайн можно не указывать', max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='online_subscription_tags',
            field=models.JSONField(blank=True, default=list, help_text='Только для онлайн: подписки/тарифы (список строк)'),
        ),
    ]
