# Generated by Django 4.2.18 on 2026-03-01 11:57

import apps.payments.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='clients.client')),
            ],
            options={
                'verbose_name': 'Installment Plan',
                'verbose_name_plural': 'Installment Plans',
            },
        ),
        migrations.CreateModel(
            name='FullPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to=apps.payments.models.receipt_upload_path)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='full_payment', to='clients.client')),
            ],
            options={
                'verbose_name': 'Full Payment',
                'verbose_name_plural': 'Full Payments',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateField()),
                ('receipt', models.ImageField(blank=True, null=True, upload_to=apps.payments.models.installment_receipt_upload_path)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.installmentplan')),
            ],
            options={
                'verbose_name': 'Installment Payment',
                'verbose_name_plural': 'Installment Payments',
                'ordering': ['paid_at'],
                'indexes': [models.Index(fields=['plan', 'paid_at'], name='payments_in_plan_id_576269_idx')],
            },
        ),
    ]
