# Generated by Django 4.2.18 on 2026-03-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_rename_clients_bon_client__idx_clients_bon_client__b66680_idx_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullpayment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_payments', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='clients.client'),
        ),
    ]
