# Generated by Django 4.2.18 on 2026-04-05 13:55

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_refundlog_retention_amount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refundlog',
            new_name='payments_re_created_4d29e6_idx',
            old_name='payments_re_created_idx',
        ),
        migrations.AlterField(
            model_name='refundlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refundlog',
            name='retention_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Удержано компанией (посещённые занятия и т.п.)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='refundlog',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Оплачено до возврата (до удержания)', max_digits=12),
        ),
    ]
