# Generated by Django 4.2.18 on 2026-04-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_payments_re_created_idx_payments_re_created_4d29e6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullpayment',
            name='course_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма курса до применения бонусного баланса; amount — итог к оплате', max_digits=12, null=True),
        ),
    ]
