# Generated by Django 4.2.18 on 2026-03-01 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_date', models.DateField()),
                ('is_absent', models.BooleanField(default=False, help_text='True = absent (НБ)')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='clients.client')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-lesson_date'],
                'indexes': [models.Index(fields=['client', 'lesson_date'], name='attendance__client__fd4d99_idx'), models.Index(fields=['lesson_date'], name='attendance__lesson__a458e6_idx'), models.Index(fields=['is_absent'], name='attendance__is_abse_510703_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('client', 'lesson_date'), name='unique_attendance_per_client_per_day'),
        ),
    ]
