# Generated by Django 4.2.18 on 2026-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='cf_srt_passphrase',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='livestream',
            name='cf_srt_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='livestream',
            name='cf_webrtc_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
