# Generated by Django 4.2.18 on 2026-04-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_add_webrtc_srt_to_livestream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='max_uses',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
