# Generated by Django 4.2.18 on 2026-05-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_fix_consultation_max_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='cf_webrtc_playback_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
