# Generated by Django 4.2.18 on 2026-05-07 20:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_rename_clients_cli_is_tria_idx_clients_cli_is_tria_5ebcf2_idx'),
        ('education', '0007_streamviewer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamGuest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Приглашён'), ('active', 'В эфире'), ('ended', 'Завершил')], default='invited', max_length=20)),
                ('jitsi_room', models.CharField(max_length=200)),
                ('jitsi_token_trainer', models.TextField(blank=True)),
                ('jitsi_token_guest', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_guests', to='clients.client')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='education.livestream')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('is_trainer', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream_chat_messages', to='clients.client')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='education.livestream')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['stream', 'created_at'], name='education_s_stream__81c1a2_idx')],
            },
        ),
    ]
