# Generated by Django 4.2.18 on 2026-05-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_stream_chat_and_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamguest',
            name='answer_sdp',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='streamguest',
            name='guest_ice',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='streamguest',
            name='offer_sdp',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='streamguest',
            name='trainer_ice',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='streamguest',
            name='jitsi_room',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
