# Generated by Django 4.2.18 on 2026-05-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_webrtc_signaling'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lessonprogress',
            name='education_l_client__583174_idx',
        ),
        migrations.AddIndex(
            model_name='livestream',
            index=models.Index(fields=['deleted_at'], name='education_l_deleted_0b53db_idx'),
        ),
        migrations.AddIndex(
            model_name='streamguest',
            index=models.Index(fields=['stream', 'status', 'deleted_at'], name='education_s_stream__5f13e1_idx'),
        ),
        migrations.AddIndex(
            model_name='streamguest',
            index=models.Index(fields=['client', 'status'], name='education_s_client__7cb153_idx'),
        ),
    ]
