# Generated by Django 4.2.18 on 2026-05-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_add_streamguest_indexes_livestream_deleted_at_idx'),
        ('education', '0010_thumbnail_url_to_text'),
    ]

    operations = [
    ]
