# Generated by Django 4.2.18 on 2026-05-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_merge_20260515_0830'),
        ('education', '0011_merge_20260515_1547'),
    ]

    operations = [
    ]
