# Generated by Django 4.2.18 on 2026-05-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_merge_20260515_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
