# Generated by Django 4.2.18 on 2026-05-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_lessonprogress_add_completed_at'),
        ('education', '0012_merge_20260515_1601'),
    ]

    operations = [
    ]
