# Generated by Django 4.2.18 on 2026-05-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_lessonprogress_add_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text')], max_length=10),
        ),
    ]
