# Generated by Django 4.2.18 on 2026-05-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_add_text_lesson_type'),
        ('education', '0013_merge_20260515_1819'),
    ]

    operations = [
    ]
