# Generated by Django 4.2.18 on 2026-05-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_merge_20260517'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lessonprogress',
            name='educ_lp_client_lwat_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonprogress',
            name='educ_lp_lesson_comp_idx',
        ),
        migrations.RemoveIndex(
            model_name='streamviewer',
            name='educ_sv_stream_active_hb_idx',
        ),
    ]
