# Generated by Django 4.2.18 on 2026-03-01 11:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('training_format', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('group_type', models.CharField(choices=[('1.5h', '1.5 hours'), ('2.5h', '2.5 hours')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expelled', 'Expelled')], default='active', max_length=20)),
                ('is_repeat', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5)),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('installment', 'Installment')], max_length=15)),
                ('registered_at', models.DateField(default=datetime.date.today)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='groups.group')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_clients', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='trainers.trainer')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-registered_at', 'last_name'],
                'indexes': [models.Index(fields=['status'], name='clients_cli_status_ce0d15_idx'), models.Index(fields=['training_format'], name='clients_cli_trainin_c8cc25_idx'), models.Index(fields=['group'], name='clients_cli_group_i_b52940_idx'), models.Index(fields=['trainer'], name='clients_cli_trainer_87baa2_idx'), models.Index(fields=['is_repeat'], name='clients_cli_is_repe_267b8e_idx'), models.Index(fields=['phone'], name='clients_cli_phone_164f4c_idx')],
            },
        ),
    ]
