# Generated by Django 4.2.18 on 2026-03-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_cabinet_login_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expelled', 'Expelled'), ('frozen', 'Frozen')], default='active', max_length=20),
        ),
    ]
