# Generated by Django 4.2.18 on 2026-03-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientgrouphistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bonustransaction',
            new_name='clients_bon_client__b66680_idx',
            old_name='clients_bon_client__idx',
        ),
        migrations.RenameIndex(
            model_name='clientgrouphistory',
            new_name='clients_cli_client__869d31_idx',
            old_name='clients_cgh_client__idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
