# Generated by Django 4.2.18 on 2026-04-05 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_bonus_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bonus_percent',
            field=models.PositiveSmallIntegerField(default=10, help_text='Процент бонуса с оплаты (0–100), задаётся при регистрации', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
