# Generated by Django 4.2.18 on 2026-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_client_group_type_optional_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registered_by_name',
            field=models.CharField(blank=True, default='', help_text='ФИО регистратора на момент записи (если пользователь удалён)', max_length=200),
        ),
    ]
