# Generated by Django 4.2.18 on 2026-04-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_clientstatushistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_is_tria_5ebcf2_idx',
            old_name='clients_cli_is_tria_idx',
        ),
    ]
