# Generated by Django 4.2.18 on 2026-05-16 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0006_alter_group_group_type_and_more'),
        ('clients', '0021_rename_clients_cli_is_tria_idx_clients_cli_is_tria_5ebcf2_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroupReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('full', 'Full'), ('installment', 'Installment')], max_length=15)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('bonus_percent', models.PositiveSmallIntegerField(default=10)),
                ('reserved_by_name', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_reservations', to='clients.client')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('reserved_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='groups.group')),
            ],
            options={
                'verbose_name': 'Бронь группы',
                'verbose_name_plural': 'Брони групп',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'used_at'], name='clients_cli_client__1bf153_idx')],
            },
        ),
    ]
