# Generated by Django 4.2.18 on 2026-05-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_clientgroupreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Заметка о клиенте (видна только сотрудникам)'),
        ),
    ]
