# Generated by Django 4.2.18 on 2026-05-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_group_type_and_more'),
        ('clients', '0023_add_client_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='second_group',
            field=models.ForeignKey(blank=True, help_text='Вторая группа (параллельное обучение)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_group_clients', to='groups.group'),
        ),
    ]
