# Generated by Django 4.2.18 on 2026-05-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_add_client_second_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='session_key',
            field=models.CharField(blank=True, default='', help_text='Rotating key embedded in JWT; new login rotates it to invalidate all old tokens', max_length=64),
        ),
    ]
