# Generated by Django 4.2.18 on 2026-05-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_add_clientaccount_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='google_email',
            field=models.EmailField(blank=True, default='', help_text='Gmail адрес ученика — менеджер указывает при регистрации.', max_length=254),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Google account sub (unique ID). Set automatically on first Google login.', max_length=128),
        ),
    ]
