# Generated by Django 4.2.18 on 2026-05-23 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_group_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0026_add_google_auth_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('full', 'Полная'), ('installment', 'Рассрочка')], max_length=15)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('bonus_percent', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_by_name', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parallel_enrollments', to='clients.client')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_enrollments', to='groups.group')),
            ],
            options={
                'verbose_name': 'Параллельная запись',
                'verbose_name_plural': 'Параллельные записи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='enrollment_receipts/')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_by_name', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_payments', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.clientenrollment')),
            ],
            options={
                'verbose_name': 'Платёж по записи',
                'verbose_name_plural': 'Платежи по записям',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientenrollment',
            index=models.Index(fields=['client', 'is_active'], name='clients_cli_client__947bc9_idx'),
        ),
    ]
